spring:
  webflux:
    base-path: /personvern/samtykke
  kafka:
    consumer:
      group-id: # consumer-personvern-samtykke-<your-instance-id>

fint:
  consumer:
    org-id:
    domain:
    package:
  kafka:
    application-id: consumer-personvern-samtykke
    enable-ssl: true
    topic:
      org-id: fintlabs.no
      domain-context: fint-core

logging:
  level:
    root: INFO
    no.fintlabs.kafka: WARN
    org:
      apache.kafka: WARN
      springframework:
        kafka: WARN
        security: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus